"""add_workflow_condition_rating_tables

Revision ID: 286f7a25e15f
Revises: 6cafd74ca767
Create Date: 2026-05-26 14:09:25.665988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '286f7a25e15f'
down_revision: Union[str, None] = '6cafd74ca767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_types',
    sa.Column('condition_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('condition_type_id')
    )
    op.create_index(op.f('ix_condition_types_condition_type_id'), 'condition_types', ['condition_type_id'], unique=False)
    op.create_table('workflow_actions',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_workflow_actions_action_id'), 'workflow_actions', ['action_id'], unique=False)
    op.create_table('conditions',
    sa.Column('condition_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type_id', sa.String(length=36), nullable=True),
    sa.Column('document_type_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['condition_type_id'], ['condition_types.condition_type_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.document_type_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_conditions_condition_id'), 'conditions', ['condition_id'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_workflow_id'), 'workflows', ['workflow_id'], unique=False)
    op.create_table('workflow_has_actions',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('next_action', sa.String(length=36), nullable=True),
    sa.Column('is_start_step', sa.Boolean(), nullable=False),
    sa.Column('condition_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['workflow_actions.action_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.condition_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['next_action'], ['workflow_actions.action_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', 'action_id')
    )
    op.create_table('workflow_instances',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('current_step_id', sa.String(length=36), nullable=True),
    sa.Column('designated_user_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_actions.action_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designated_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_index(op.f('ix_workflow_instances_instance_id'), 'workflow_instances', ['instance_id'], unique=False)
    op.create_table('workflow_instance_steps',
    sa.Column('instance_step_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['workflow_actions.action_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.instance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_step_id')
    )
    op.create_index(op.f('ix_workflow_instance_steps_instance_step_id'), 'workflow_instance_steps', ['instance_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instance_steps_instance_step_id'), table_name='workflow_instance_steps')
    op.drop_table('workflow_instance_steps')
    op.drop_index(op.f('ix_workflow_instances_instance_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_table('workflow_has_actions')
    op.drop_index(op.f('ix_workflows_workflow_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_conditions_condition_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_workflow_actions_action_id'), table_name='workflow_actions')
    op.drop_table('workflow_actions')
    op.drop_index(op.f('ix_condition_types_condition_type_id'), table_name='condition_types')
    op.drop_table('condition_types')
    # ### end Alembic commands ###
