"""add step_order to workflow_instance_steps

Revision ID: 293447082ba2
Revises: afafd56a06b5
Create Date: 2026-06-17 15:51:58.975638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '293447082ba2'
down_revision: Union[str, None] = 'afafd56a06b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('workflow_instance_steps', sa.Column('step_order', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('workflow_instance_steps', 'step_order', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_instance_steps', 'step_order')
    # ### end Alembic commands ###
