"""add sprint1 models

Revision ID: 2e9d464070bd
Revises: 55c71b0b109a
Create Date: 2026-05-23 09:54:09.222482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e9d464070bd'
down_revision: Union[str, None] = '55c71b0b109a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_type_id')
    )
    op.create_index(op.f('ix_document_types_document_type_id'), 'document_types', ['document_type_id'], unique=False)
    op.create_table('section_templates',
    sa.Column('section_template_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('content_structure', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.document_type_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('section_template_id')
    )
    op.create_index(op.f('ix_section_templates_section_template_id'), 'section_templates', ['section_template_id'], unique=False)
    op.create_table('document_ratings',
    sa.Column('document_rating_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_rating_id')
    )
    op.create_index(op.f('ix_document_ratings_document_rating_id'), 'document_ratings', ['document_rating_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('document_section_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_template_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_template_id'], ['section_templates.section_template_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('document_section_id')
    )
    op.create_index(op.f('ix_document_sections_document_section_id'), 'document_sections', ['document_section_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_version_id')
    )
    op.create_index(op.f('ix_document_versions_document_version_id'), 'document_versions', ['document_version_id'], unique=False)
    op.add_column('documents', sa.Column('document_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_types', ['document_type_id'], ['document_type_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type_id')
    op.drop_index(op.f('ix_document_versions_document_version_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_sections_document_section_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_document_ratings_document_rating_id'), table_name='document_ratings')
    op.drop_table('document_ratings')
    op.drop_index(op.f('ix_section_templates_section_template_id'), table_name='section_templates')
    op.drop_table('section_templates')
    op.drop_index(op.f('ix_document_types_document_type_id'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
