"""add file path to documents

Revision ID: 55c71b0b109a
Revises: 220b1778ff0f
Create Date: 2026-05-19 14:59:23.227888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55c71b0b109a'
down_revision: Union[str, None] = '220b1778ff0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
