"""move step_order to workflow_has_actions

Revision ID: 68c0e2584ac9
Revises: 293447082ba2
Create Date: 2026-06-17 15:56:14.775518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68c0e2584ac9'
down_revision: Union[str, None] = '293447082ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_has_actions', sa.Column('step_order', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('workflow_has_actions', 'step_order', server_default=None)
    op.drop_column('workflow_instance_steps', 'step_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_instance_steps', sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('workflow_has_actions', 'step_order')
    # ### end Alembic commands ###
