"""remove document_ratings table

Revision ID: 75a6706b69aa
Revises: 94da9e8db566
Create Date: 2026-06-03 11:48:50.626070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75a6706b69aa'
down_revision: Union[str, None] = '94da9e8db566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_ratings_document_rating_id', table_name='document_ratings')
    op.drop_table('document_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_ratings',
    sa.Column('document_rating_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='document_ratings_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='document_ratings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_rating_id', name='document_ratings_pkey')
    )
    op.create_index('ix_document_ratings_document_rating_id', 'document_ratings', ['document_rating_id'], unique=False)
    # ### end Alembic commands ###
