"""replace full_content with file_path and file_name on document_versions

Revision ID: 82db20228858
Revises: 68c0e2584ac9
Create Date: 2026-06-17 16:16:17.097732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82db20228858'
down_revision: Union[str, None] = '68c0e2584ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('document_versions', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.drop_column('document_versions', 'full_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('full_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('document_versions', 'file_name')
    op.drop_column('document_versions', 'file_path')
    # ### end Alembic commands ###
