"""add instance_step_id to document_versions

Revision ID: 94da9e8db566
Revises: d89eab50e848
Create Date: 2026-05-26 18:44:54.188155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94da9e8db566'
down_revision: Union[str, None] = 'd89eab50e848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('instance_step_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'document_versions', 'workflow_instance_steps', ['instance_step_id'], ['instance_step_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_column('document_versions', 'instance_step_id')
    # ### end Alembic commands ###
