"""add file_type to documents

Revision ID: a8d0958bdf32
Revises: 82db20228858
Create Date: 2026-06-17 16:28:45.021604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8d0958bdf32'
down_revision: Union[str, None] = '82db20228858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
