"""tasks

Revision ID: b4c4f5aa8507
Revises: 5d8075c90e23
Create Date: 2026-05-21 08:59:41.962345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4c4f5aa8507'
down_revision: Union[str, None] = '5d8075c90e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
