"""tasks_uuid

Revision ID: b625415fa13a
Revises: 6cafd74ca767
Create Date: 2026-05-25 19:10:42.046288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b625415fa13a'
down_revision: Union[str, None] = '6cafd74ca767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'not_active', name='resourcestatus'), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resource_resource_id'), 'resource', ['resource_id'], unique=False)
    op.create_table('task_workflow',
    sa.Column('task_workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_workflow_id')
    )
    op.create_index(op.f('ix_task_workflow_task_workflow_id'), 'task_workflow', ['task_workflow_id'], unique=False)
    op.create_table('task_workflow_step',
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('task_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('next_step_id', sa.String(length=36), nullable=True),
    sa.Column('is_first', sa.Boolean(), nullable=True),
    sa.Column('is_last', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['next_step_id'], ['task_workflow_step.step_id'], ),
    sa.ForeignKeyConstraint(['task_workflow_id'], ['task_workflow.task_workflow_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_task_workflow_step_step_id'), 'task_workflow_step', ['step_id'], unique=False)
    op.create_table('task',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='taskpriority'), nullable=True),
    sa.Column('current_step_id', sa.String(length=36), nullable=True),
    sa.Column('task_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['current_step_id'], ['task_workflow_step.step_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['task_workflow_id'], ['task_workflow.task_workflow_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_task_id'), 'task', ['task_id'], unique=False)
    op.create_table('subtask',
    sa.Column('subtask_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.Enum('created', 'in_progress', 'done', name='subtaskstatus'), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('subtask_id')
    )
    op.create_index(op.f('ix_subtask_subtask_id'), 'subtask', ['subtask_id'], unique=False)
    op.create_table('task_resource',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reserved_from', sa.DateTime(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('free', 'reserved', 'in_use', name='taskresourcestatus'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    op.create_table('task_status_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('subtask_id', sa.String(length=36), nullable=True),
    sa.Column('old_step_id', sa.String(length=36), nullable=True),
    sa.Column('new_step_id', sa.String(length=36), nullable=True),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['new_step_id'], ['task_workflow_step.step_id'], ),
    sa.ForeignKeyConstraint(['old_step_id'], ['task_workflow_step.step_id'], ),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtask.subtask_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_task_status_history_history_id'), 'task_status_history', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_history_history_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_table('task_resource')
    op.drop_index(op.f('ix_subtask_subtask_id'), table_name='subtask')
    op.drop_table('subtask')
    op.drop_index(op.f('ix_task_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_task_workflow_step_step_id'), table_name='task_workflow_step')
    op.drop_table('task_workflow_step')
    op.drop_index(op.f('ix_task_workflow_task_workflow_id'), table_name='task_workflow')
    op.drop_table('task_workflow')
    op.drop_index(op.f('ix_resource_resource_id'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
