"""add_document_type_to_workflow

Revision ID: d89eab50e848
Revises: 286f7a25e15f
Create Date: 2026-05-26 17:35:36.159725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd89eab50e848'
down_revision: Union[str, None] = '286f7a25e15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('document_type_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'workflows', 'document_types', ['document_type_id'], ['document_type_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'document_type_id')
    # ### end Alembic commands ###
