from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class UsageSummary(BaseModel):
    total_generations: int
    total_tokens: int
    prompt_tokens: int
    completion_tokens: int
    estimated_cost: float
    avg_latency_ms: float
    unique_documents: int


class TimeSeriesPoint(BaseModel):
    date: str
    generations: int
    total_tokens: int
    prompt_tokens: int
    completion_tokens: int
    estimated_cost: float


class BreakdownItem(BaseModel):
    label: str
    generations: int
    total_tokens: int
    estimated_cost: float


class RecentGeneration(BaseModel):
    llm_usage_log_id: str
    created_at: Optional[datetime] = None
    generation_type: str
    model: Optional[str] = None
    document_name: Optional[str] = None
    document_type_name: Optional[str] = None
    user_name: Optional[str] = None
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    estimated_cost: Optional[float] = None
    latency_ms: Optional[int] = None


class DashboardResponse(BaseModel):
    summary: UsageSummary
    time_series: List[TimeSeriesPoint]
    by_document_type: List[BreakdownItem]
    by_user: List[BreakdownItem]
    recent: List[RecentGeneration]


# --- Persisted reports (generated by the generate_usage_report procedure) ---

class GenerateReportRequest(BaseModel):
    start: Optional[datetime] = None
    end: Optional[datetime] = None


class ReportItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    label: str
    generations: int
    total_tokens: int
    estimated_cost: Optional[float] = None


class ReportSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    report_id: str
    title: str
    period_start: datetime
    period_end: datetime
    generated_at: datetime
    total_generations: int
    total_tokens: int
    total_cost: Optional[float] = None


class ReportDetail(ReportSummary):
    items: List[ReportItem] = []
